[book]
authors = ["ysykzheng"]
language = "en"
multilingual = false
src = "src"
title = "AI for Technical Writing: Techniques and Strategies for Creating Clear and Concise Documentation with Technology"
